#!/usr/bin/env python
# coding: utf-8

# Copyright 2017 Hyeon Kim
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

from __future__ import print_function, unicode_literals, absolute_import
import sys
from base64 import b64encode
if sys.version_info >= (3,):
    import pickle
else:
    import cPickle as pickle

from cloudkeeper import prompt

if __name__ == '__main__':
    data = prompt.ask()
    # Serialize the data
    serialized = b64encode(pickle.dumps(data, 2)).decode()
    print(serialized)
    print('\x1b[34mPassing the data to the original process\x1b[0m', file=sys.stderr)
