#!/usr/bin/env python
# coding: utf-8

# Copyright 2017 Hyeon Kim
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

from __future__ import print_function, unicode_literals
import sys
from base64 import b64encode
from getpass import getpass
if sys.version_info >= (3,):
    import pickle
else:
    import cPickle as pickle
    input = raw_input

def prompt():
    print('Logging in to the IRCCloud server\n', file=sys.stderr)

    # Get email address
    print('     email : ', end='', file=sys.stderr)
    sys.stderr.flush()
    email = input()

    # Get password
    print('  password : ', end='', file=sys.stderr)
    sys.stderr.flush()
    password = getpass('')

    return (email, password)

if __name__ == '__main__':
    data = prompt()
    # Serialize object
    serialized = b64encode(pickle.dumps(data, 2)).decode()
    print(serialized)
