#!/usr/bin/env python
# coding: utf-8

# Copyright 2017 Hyeon Kim
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

import sys
from base64 import b64encode
if sys.version_info >= (3,):
    import pickle
else:
    import cPickle as pickle

from src.prompt import prompt

if __name__ == '__main__':
    data = prompt()
    # Serialize the data
    serialized = b64encode(pickle.dumps(data, 2)).decode()
    print(serialized)
